/**
 * Fonction utilitaire pour inclure un fichier HTML dans un template.
 * Utilisé via <?!= include('NomDuFichier') ?> dans les fichiers HTML.
 */
function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename).getContent();
}

/**
 * Retourne un texte traduit côté serveur selon la langue de l'utilisateur.
 * @param {string} key - La clé du texte à traduire.
 * @return {string} Le texte traduit.
 */
function T_(key) {
  const isEn = Session.getActiveUserLocale().startsWith('en');
  const texts = {
    // Rapport
    timeReport: isEn ? 'Time Report' : 'Rapport de temps',
    hoursSummary: isEn ? 'Hours Recording Summary' : "Résumé de l'enregistrement des heures",
    projects: isEn ? 'Projects' : 'Projets',
    calendar: isEn ? 'Calendar' : 'Calendrier',
    hourlyDetails: isEn ? 'Hourly Details' : 'Détails horaire',
    details: isEn ? 'Details' : 'Détails',
    hoursPerProject: isEn ? 'Hours per Project' : 'Heures par projet',
    totalHours: isEn ? 'Total Hours' : 'Total des heures',
    miscTasks: isEn ? 'Miscellaneous tasks' : 'Tâches diverses',
    from: isEn ? 'from ' : 'du ',
    to: isEn ? ' to ' : ' au ',
    invalidPeriod: isEn ? 'Invalid specified period' : 'Période spécifiée non valide',
    // Timer
    eventCreated: isEn ? 'Event created successfully!' : "L'événement a été créé avec succès !",
    calendarNotFound: isEn ? 'Calendar not found.' : 'Calendrier non trouvé.',
    // Export
    reportGenerated: isEn ? 'Report generated successfully!' : 'Le rapport a été généré avec succès !',
    done: isEn ? 'Done' : 'Terminé',
    // Email
    emailSubject: isEn ? 'Time Report: ' : 'Rapport de Temps : ',
    emailIntro: isEn ? 'Please find below the summary of your recorded time:' : 'Veuillez trouver ci-dessous le résumé de vos temps enregistrés :',
    emailFooter: isEn ? 'This report was automatically generated by GWorkspace Timesheet.' : "Ce rapport a été généré automatiquement par GWorkspace Timesheet.",
    emailFallback: isEn ? 'Your email client does not support HTML.' : 'Votre client de messagerie ne supporte pas le HTML.',
    emailSent: isEn ? 'Email sent successfully to ' : "L'email a été envoyé avec succès à ",
    emailSentTitle: isEn ? 'Email Sent' : 'Email Envoyé',
    emailError: isEn ? "Unable to retrieve the active user's email address." : "Impossible de récupérer l'adresse email de l'utilisateur actif.",
    // À propos
    aboutDev: isEn ? 'Developed by Fabrice Faucheux' : 'Développé par Fabrice Faucheux',
    aboutLinkedIn: isEn ? 'Find me on LinkedIn' : 'Me retrouver sur LinkedIn',
    aboutDonate: isEn ? 'If you would like to support my work, you can make a donation via PayPal:' : 'Si vous souhaitez soutenir mon travail, vous pouvez faire un don via PayPal :',
    aboutDonateBtn: isEn ? 'Support via PayPal' : 'Soutenir via PayPal',
    aboutTitle: isEn ? 'About' : 'À propos',
  };
  return texts[key] || key;
}

/**
 * Applique la mise en forme au rapport généré.
 * @param {GoogleAppsScript.Spreadsheet.Sheet} feuille - La feuille à formater.
 */
function miseEnForme(feuille) {
  const totalColonnes = feuille.getMaxColumns();
  const colonneF = 6;
  
  const colonnesASupprimer = totalColonnes - colonneF + 1;
  
  if (colonnesASupprimer > 0) {
    feuille.deleteColumns(colonneF, colonnesASupprimer);
  }
  
  feuille.setColumnWidth(1, 140);
  feuille.setColumnWidth(2, 140);
  feuille.setColumnWidth(3, 270);
  feuille.setColumnWidth(4, 180);
  feuille.setColumnWidth(5, 140);

  feuille.getRange("C1").setValue(T_('timeReport')).setFontWeight("bold").setFontSize(24);

  feuille.getRange("A5").setValue(T_('hoursSummary')).setFontWeight("bold").setFontSize(12);
  feuille.getRange("A5:E5").setBorder(null, null, true, null, null, null, null, SpreadsheetApp.BorderStyle.SOLID);

  feuille.getRange("A6").setValue(T_('projects')).setFontWeight("bold");
  feuille.getRange("D6").setValue(T_('calendar')).setFontWeight("bold");

  feuille.getRange("C1:C2").setVerticalAlignment("middle").setHorizontalAlignment("center");

  const derniereLigne = feuille.getLastRow();
  if (derniereLigne >= 6) {
    feuille.getRange("E7:E" + derniereLigne).setNumberFormat("#,##0.00");
  }
}

function obtenirCalendriers() {
  const calendriers = CalendarApp.getAllCalendars();
  return calendriers.map(calendrier => ({
    id: calendrier.getId(),
    nom: calendrier.getName()
  }));
}

function compteurNomFeuille(ss, nomBase) {
  const feuilles = ss.getSheets();
  const nomExistant = feuilles.map(feuille => feuille.getName());
  let compteur = 1;
  let nomFeuille = nomBase;

  while (nomExistant.includes(nomFeuille)) {
    nomFeuille = `${nomBase} (${compteur})`;
    compteur++;
  }

  return nomFeuille;
}

function formaterDate(date) {
  return Utilities.formatDate(date, Session.getScriptTimeZone(), "dd/MM/yyyy");
}
